#!/usr/bin/env zsh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# use tiling layout
yabai -m config layout bsp

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding 40
yabai -m config bottom_padding 40
yabai -m config left_padding 40
yabai -m config right_padding 40
yabai -m config window_gap 40

# auto balance window width
yabai -m config auto_balance on

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# modify window shadows (default: on, options: on, off, float)
yabai -m config window_shadow on

# window opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.85
yabai -m config normal_window_opacity 0.5

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
